networks:
  eda-network:
    driver: bridge

volumes:
  pgdata:

services:
  postgres:
    image: postgres:18
    networks:
      - eda-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eda_user
      POSTGRES_PASSWORD: eda_password
      POSTGRES_DB: eda_db
    volumes:
      - pgdata:/var/lib/postgresql
      - ./docker/postgres-init:/docker-entrypoint-initdb.d

  kafka:
    image: apache/kafka:4.1.1
    networks:
      - eda-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:8.0.3
    networks:
      - eda-network
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
